/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import poly.cafe.dao.CategoryDAO;
import poly.cafe.dao.impl.BillDetailDAOImpl;
import poly.cafe.dao.impl.CategoryDAOImpl;
import poly.cafe.dao.impl.FoodDAOImpl;
import poly.cafe.entity.Bill;
import poly.cafe.entity.BillDetail;
import poly.cafe.entity.Category;
import poly.cafe.entity.Food;
import poly.cafe.util.XDialog;
import poly.cafe.dao.FoodDAO;
import poly.cafe.dao.InventoryDAO;
import poly.cafe.dao.impl.InventoryDAOImpl;
import poly.cafe.entity.Inventory;
import poly.cafe.ui.controller.FoodController;

/**
 *
 * @author Admin
 */
public class FoodJDialog extends javax.swing.JDialog implements FoodController {
    private List<Food> availableFoods = new ArrayList<>();
    private Bill bill;
    private CategoryDAO categoryDao = new CategoryDAOImpl();
    private FoodDAO foodDao = new FoodDAOImpl();
    private InventoryDAO inventoryDao = new InventoryDAOImpl();
    private List<Category> categories = List.of();
    private List<Food> foods = List.of();

    public void setBill(Bill bill) {
        this.bill = bill;
    }


    /**
     * Creates new form Drink1
     */
    public FoodJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblFoods = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Sách Món");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblFoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Món", "Tên Món", "Đơn Giá", "Giảm Giá", "Trạng Thái"
            }
        ));
        tblFoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFoods);

        tblCategorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Loại"
            }
        ));
        tblCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategorieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategorie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategorieMouseClicked
        // TODO add your handling code here:
        this.fillFoods();
    }//GEN-LAST:event_tblCategorieMouseClicked

    private void tblFoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.addFoodToBill();
        }
    }//GEN-LAST:event_tblFoodsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened


    public void open() {
        this.setLocationRelativeTo(null);
        this.fillCategories();
        this.fillFoods();
    }

    // Đoạn 1: Sửa fillCategories để kiểm tra categories rỗng trước khi setRowSelectionInterval
    public void fillCategories() {
        categories = categoryDao.findAll();
        DefaultTableModel model = (DefaultTableModel) tblCategorie.getModel();
        model.setRowCount(0);
        categories.forEach(d -> model.addRow(new Object[]{d.getName()}));
        if (!categories.isEmpty()) { // Sửa tại đây
            tblCategorie.setRowSelectionInterval(0, 0);
        }
    }

// Đoạn 2: Sửa fillDrinks để kiểm tra categories rỗng và chỉ số dòng hợp lệ
    // SỬA: Khi fillDrinks, chỉ hiển thị đồ uống còn hàng (isAvailable)
    public void fillFoods() {
        if (categories.isEmpty()) {
            return;
        }
        int catRow = tblCategorie.getSelectedRow();
        if (catRow < 0 || catRow >= categories.size()) {
            return;
        }
        Category category = categories.get(catRow);
        foods = foodDao.findByCategoryId(category.getId());
        DefaultTableModel model = (DefaultTableModel) tblFoods.getModel();
        model.setRowCount(0);
        availableFoods.clear();
        for (Food d : foods) {
            if (d.isAvailable()) {
                Object[] row = {
                    d.getId(),
                    d.getName(),
                    String.format("$%.1f", d.getUnitPrice()),
                    String.format("%.0f%%", d.getDiscount() * 100)
                };
                model.addRow(row);
                availableFoods.add(d);
            }
        }
    }

// Đoạn 3: Sửa addDrinkToBill để kiểm tra bill, bill.getId() và chỉ số dòng hợp lệ
     public void addFoodToBill() {
        int productRow = tblFoods.getSelectedRow();
        if (bill == null || bill.getId() == null) {
            XDialog.alert("Phiếu chưa được tạo hoặc không hợp lệ!");
            return;
        }
        if (availableFoods.isEmpty() || productRow < 0 || productRow >= availableFoods.size()) {
            XDialog.alert("Vui lòng chọn món!");
            return;
        }
        String quantity = XDialog.prompt("Số lượng?");
        if (quantity != null && !quantity.isEmpty()) {
            try {
                int qty = Integer.parseInt(quantity);
                if (qty < 1) {
                    throw new NumberFormatException();
                }

                Food food = availableFoods.get(productRow);
                Inventory inv = inventoryDao.findById(food.getId());
                if (inv == null) {
                    XDialog.warning("Không tìm thấy tồn kho cho sản phẩm này!");
                    return;
                }
                // KIỂM TRA TỒN KHO TRƯỚC KHI THÊM
                if (inv.getQuantity() < qty) {
                    XDialog.warning("Không đủ số lượng!");
                    return;
                }
                // Trừ tồn kho
                inv.setQuantity(inv.getQuantity() - qty);
                inventoryDao.update(inv);

                // Nếu hết hàng thì cập nhật trạng thái sản phẩm
                if (inv.getQuantity() == 0) {
                    food.setAvailable(false);
                    foodDao.update(food);
                }

                // Thêm hoặc cập nhật BillDetail
                BillDetailDAOImpl billDetailDao = new BillDetailDAOImpl();
                BillDetail existingDetail = billDetailDao.findByBillIdAndFoodId(bill.getId(), food.getId());
                if (existingDetail != null) {
                    existingDetail.setQuantity(existingDetail.getQuantity() + qty);
                    billDetailDao.update(existingDetail);
                    XDialog.alert("Đã cập nhật số lượng sản phẩm trong phiếu!");
                } else {
                    BillDetail detail = new BillDetail();
                    detail.setBillId(bill.getId());
                    detail.setFoodId(food.getId());
                    detail.setUnitPrice(food.getUnitPrice());
                    detail.setDiscount(food.getDiscount());
                    detail.setQuantity(qty);
                    billDetailDao.create(detail);
                    XDialog.alert("Đã thêm sản phẩm vào phiếu!");
                }
                this.dispose();
            } catch (NumberFormatException ex) {
                XDialog.alert("Số lượng phải là số nguyên dương!");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FoodJDialog dialog = new FoodJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCategorie;
    private javax.swing.JTable tblFoods;
    // End of variables declaration//GEN-END:variables
}
