/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

import java.awt.Color;
import poly.cafe.ui.controller.PolyCafeController;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.Timer;
import poly.cafe.ui.manager.BillManagerJDialog;
import poly.cafe.ui.manager.CardManagerJDialog;
import poly.cafe.ui.manager.CategoryManagerJDialog;
import poly.cafe.ui.manager.FoodManagerJDialog;
import poly.cafe.ui.manager.InventoryManagerJDialog;
import poly.cafe.ui.manager.RevenueManagerJDialog;
import poly.cafe.ui.manager.UserManagerJDialog;
import poly.cafe.util.XAuth;
import poly.cafe.util.XIcon;

/**
 *
 * @author Admin
 */
public class Menu2025JFrame extends javax.swing.JFrame implements PolyCafeController{

    /**
     * Creates new form PolyCafeJFrame2025
     */
    public Menu2025JFrame() {
        initComponents();
        init();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeftBottom = new javax.swing.JPanel();
        btnSale = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlManager = new javax.swing.JPanel();
        btnFoodManager = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnCategoryManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnCardManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        btnInvetoryManager = new javax.swing.JButton();
        pntLeftTop = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bếp nhà bông");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlLeftBottom.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        btnSale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSale.setText("Bán Hàng");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnSale);

        btnHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistory.setText("Lịch Sử");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnHistory);

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChangePassword.setText("Đổi Mật Khẩu");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnChangePassword);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Đăng Xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnLogout);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Kết Thúc");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlLeftBottom.add(btnExit);

        pnlCenter.setBackground(new java.awt.Color(255, 204, 204));

        pnlImage.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Banner.png"))); // NOI18N

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlManager.setBackground(new java.awt.Color(255, 204, 204));
        pnlManager.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        btnFoodManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFoodManager.setText("Món");
        btnFoodManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnFoodManager);

        btnBillManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBillManager.setText("Phiếu Bán Hàng");
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnBillManager);

        btnCategoryManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCategoryManager.setText("Loại món");
        btnCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCategoryManager);

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserManager.setText("Tài Khoản");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnUserManager);

        btnCardManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCardManager.setText("Thẻ Bàn");
        btnCardManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnCardManager);

        btnRevenueManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRevenueManager.setText("Doanh Thu");
        btnRevenueManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnRevenueManager);

        btnInvetoryManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInvetoryManager.setText("Kho Nguyên Liệu");
        btnInvetoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvetoryManagerActionPerformed(evt);
            }
        });
        pnlManager.add(btnInvetoryManager);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManager, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pntLeftTop.setForeground(new java.awt.Color(255, 255, 255));

        lblPhoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N

        lblFullname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFullname.setText("Username");

        javax.swing.GroupLayout pntLeftTopLayout = new javax.swing.GroupLayout(pntLeftTop);
        pntLeftTop.setLayout(pntLeftTopLayout);
        pntLeftTopLayout.setHorizontalGroup(
            pntLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntLeftTopLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pntLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pntLeftTopLayout.setVerticalGroup(
            pntLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntLeftTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFullname)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pntLeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlLeftBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pntLeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLeftBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        this.showHistoryJDialog(this);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        // TODO add your handling code here:
        new SalesJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnSaleActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        new ChangePasswordJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnFoodManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodManagerActionPerformed
        // TODO add your handling code here:
        new FoodManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnFoodManagerActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        // TODO add your handling code here:
        new BillManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryManagerActionPerformed
        // TODO add your handling code here:
        new CategoryManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnCategoryManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        // TODO add your handling code here:
        new UserManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnCardManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardManagerActionPerformed
        // TODO add your handling code here:
        new CardManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnCardManagerActionPerformed

    private void btnRevenueManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueManagerActionPerformed
        // TODO add your handling code here:
        new RevenueManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnRevenueManagerActionPerformed

    private void btnInvetoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvetoryManagerActionPerformed
        // TODO add your handling code here:
        new InventoryManagerJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnInvetoryManagerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        XAuth.user = null;
        this.showLoginJDialog(this);
        // Kiểm tra nếu user đăng nhập thành công
        if (XAuth.user != null) {
            this.init1();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2025JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2025JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2025JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2025JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2025JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnCardManager;
    private javax.swing.JButton btnCategoryManager;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFoodManager;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnInvetoryManager;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnSale;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlLeftBottom;
    private javax.swing.JPanel pnlManager;
    private javax.swing.JPanel pntLeftTop;
    // End of variables declaration//GEN-END:variables

  @Override
    public void init() {
        this.setIconImage(XIcon.getIcon("logo.jpg").getImage());
        this.setLocationRelativeTo(null);

        this.showWelcomeJDialog(this);
        this.showLoginJDialog(this);

        String photoName = XAuth.user.getPhoto();
        if (photoName == null || photoName.isBlank()) {
            photoName = "logo.jpg"; // hoặc ảnh mặc định
        }
        File file = new File("photos", photoName);
        if (file.exists()) {
            XIcon.setIcon(lblPhoto, file);
        } else {
            // Thử tìm trong resource icons
            java.net.URL url = getClass().getResource("/poly/cafe/icons/" + photoName);
            if (url == null) {
                // Thử tiếp trong resource img (tuỳ project)
                url = getClass().getResource("/img/" + photoName);
            }
            if (url != null) {
                lblPhoto.setIcon(new javax.swing.ImageIcon(url));
            } else {
                // fallback ảnh mặc định
                java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/logo.jpg");
                lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);
            }
        }
        lblFullname.setText(XAuth.user.getFullname());

        if (XAuth.user.isManager()) {
            // Quản lý: hiện đầy đủ các chức năng
            pnlManager.setVisible(true);
            btnRevenueManager.setVisible(true);
            btnUserManager.setVisible(true);
            btnCategoryManager.setVisible(true);
            btnFoodManager.setVisible(true);
            btnBillManager.setVisible(true);
            btnCardManager.setVisible(true);
            btnInvetoryManager.setVisible(true);
        } else {
            // Nhân viên: Ẩn các chức năng quản lý không cần thiết
            btnRevenueManager.setVisible(false);
            btnUserManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnFoodManager.setVisible(false);
            btnBillManager.setVisible(false);
            btnCardManager.setVisible(false);
            btnInvetoryManager.setVisible(false);
        }
    }
       public void init1() {
        this.setIconImage(XIcon.getIcon("logo.jpg").getImage());
        this.setLocationRelativeTo(null);
        // Kiểm tra đăng nhập
        if (XAuth.user == null) {
            lblFullname.setText("Khách");
            java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/logo.jpg");
            lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);

            pnlManager.setVisible(false); // Ẩn toàn bộ quản lý
            return; // dừng lại vì không có người dùng
        }

        String photoName = XAuth.user.getPhoto();
        if (photoName == null || photoName.isBlank()) {
            photoName = "logo.jpg";
        }

        File file = new File("photos", photoName);
        if (file.exists()) {
            XIcon.setIcon(lblPhoto, file);
        } else {
            java.net.URL url = getClass().getResource("/poly/cafe/icons/" + photoName);
            if (url == null) {
                url = getClass().getResource("/img/" + photoName);
            }
            if (url != null) {
                lblPhoto.setIcon(new javax.swing.ImageIcon(url));
            } else {
                java.net.URL defaultUrl = getClass().getResource("/poly/cafe/icons/logo.jpg");
                lblPhoto.setIcon(defaultUrl != null ? new javax.swing.ImageIcon(defaultUrl) : null);
            }
        }

        lblFullname.setText(XAuth.user.getFullname());

        if (XAuth.user.isManager()) {
             pnlManager.setVisible(true);
            btnRevenueManager.setVisible(true);
            btnUserManager.setVisible(true);
            btnCategoryManager.setVisible(true);
            btnFoodManager.setVisible(true);
            btnBillManager.setVisible(true);
            btnCardManager.setVisible(true);
            btnInvetoryManager.setVisible(true);
        } else {
            btnRevenueManager.setVisible(false);
            btnUserManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnFoodManager.setVisible(false);
            btnBillManager.setVisible(false);
            btnCardManager.setVisible(false);
            btnInvetoryManager.setVisible(false);
        }
    }
Color pink = new Color(255,204,204); // hoặc mã màu hồng bạn muốn



    
}
